name: 'Pipeline 1 - Infraestructura base'

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  workflow_dispatch:

jobs:
  validacion:
    name: '2. Validacion y Lint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./infra

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ./infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

  plan:
    name: '3. Plan de Infraestructura'
    needs: validacion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ./infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infra

  apply:
    name: '5. Apply y Provisionamiento'
    needs: plan
    environment: produccion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ./infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra
